# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

keychain_name = "temp"
keychain_password = "temp"

def delete_temp_keychain(name)
  delete_keychain(
    name: name,
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false,
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Builds the ipa file"
  lane :build do
    ensure_temp_keychain(keychain_name, keychain_password)
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end
    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: "temp",
      keychain_password: "temp",
    )
    automatic_code_signing(
      use_automatic_signing: false,
    )
    update_code_signing_settings(
      use_automatic_signing: false,
    )
    gym()
    delete_temp_keychain(keychain_name)
  end

  desc "Deploy a new beta"
  lane :distribute_beta do |options|
    # Upload to test flight or AppStore depending on caller parameters
    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APPID"],
      groups: "ios-testers",
      release_notes: "Try out the new version",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: ENV["FIREBASE_CI_TOKEN"],
      ipa_path: "./build/Runner/Runner.ipa",
    )
  end
end
