# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds the ipa file"
  lane :beta do
     match
     gym
  end
end
