# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Builds the ipa file"
  lane :beta do
     create_keychain(
         name: "temp",
         password: "temp",
         default_keychain: true,
         unlock: true,
         timeout: 3600,
         lock_when_sleeps: false
      )
     match(
        type: "development",
        readonly: is_ci,
        keychain_name: "temp",
        keychain_password: "temp"
        )
     gym
  end
end
