name: CI

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Dart/Flutter Package Analyzer
      uses: axel-op/dart-package-analyzer@v2
      with:
        # Token to connect to Github. Use secrets.GITHUB_TOKEN
        githubToken: secrets.GITHUB_TOKEN
