name: Beta Rollout
on:
  push:
    branches:
      - master

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Cleaning flutter
        run: flutter clean
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload iPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos/app.ipa
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter build apk
      #- run: flutter build appbundle --target-platform android-arm,android-arm64
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  #  deploy_web:
  #    name: Deploy Web to Firebase Hosting
  #    needs: build_web
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout Repo
  #        uses: actions/checkout@v2
  #      - name: Download Artifact
  #        uses: actions/download-artifact@v2
  #        with:
  #          name: web-build
  #      - name: Deploy to Firebase
  #        uses: w9jds/firebase-action@master
  #        with:
  #          args: deploy --only hosting --public web-build
  #        env:
  #          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #          PROJECT_ID: default
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-build
      - name: Upload IPA
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_IOS_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: ios-testers
          file: app.ipa
          debug: true
  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: android-testers
          file: app-release.apk
          debug: true
